module.exports = {
  foods: [
    {
      _id: "1",
      title: "Chicken Soup",
      category: "Soup",
      imgSource: "/images/1.jpg",
      price: 96,
      rating: 3.5,
      countInTheKitchen: 0,
    },
    {
      _id: "2",
      title: "Chicken Soup 2",
      category: "Soup",
      imgSource: "/images/2.jpg",
      price: 96,
      rating: 3.5,
      countInTheKitchen: 9,
    },
    {
      _id: "3",
      title: "Chicken Soup 3",
      category: "Soup",
      imgSource: "/images/3.jpg",
      price: 96,
      rating: 3.5,
      countInTheKitchen: 6,
    },
    {
      _id: "4",
      title: "Chicken Soup 4",
      category: "Soup",
      imgSource: "/images/4.jpg",
      price: 96,
      rating: 3.5,
      countInTheKitchen: 4,
    },
    {
      _id: "5",
      title: "Chicken Soup 5",
      category: "Soup",
      imgSource: "/images/5.jpg",
      price: 96,
      rating: 3.5,
      countInTheKitchen: 2,
    },
  ],
};
