export default {
  foods: [
    {
      _id: "1",
      title: "Chicken Soup",
      category: "Soup",
      imgSource: "/images/1.jpg",
      price: 96,
      rating: 3.5,
      category: 'Soup',
    },
    {
        _id: "2",
        title: "Chicken Soup 2",
        category: "Soup",
        imgSource: "/images/2.jpg",
        price: 96,
        rating: 3.5,
        category: 'Rice',
      },
      {
        _id: "3",
        title: "Chicken Soup 3",
        category: "Soup",
        imgSource: "/images/3.jpg",
        price: 96,
        rating: 3.5,
        category: 'Soup',
      },
      {
        _id: "4",
        title: "Chicken Soup 4",
        category: "Soup",
        imgSource: "/images/4.jpg",
        price: 96,
        rating: 3.5,
        category: 'Noodle',
      },
      {
        _id: "5",
        title: "Chicken Soup 5",
        category: "Soup",
        imgSource: "/images/5.jpg",
        price: 96,
        rating: 3.5,
        category: 'Noodle',
      },
    
  ],
};
